'''
returns dictionaries of company list with its stock maeket name

references:

* Largest Companies by Market Cap Today (TOP 50 LIST)
https://www.dogsofthedow.com/largest-companies-by-market-cap.htm

* US STOCK MARKET
https://www.tradingview.com/markets/stocks-usa/market-movers-large-cap/

* The 100 largest companies in the world by market capitalization in 2021
https://www.statista.com/statistics/263264/top-companies-in-the-world-by-market-capitalization/

* Largest Companies by Market Cap
https://companiesmarketcap.com/
'''

# Declare a dictionary with company full name as key
companies = {
	'Apple': 'AAPL',
	'Microsoft': 'MSFT',
	'Alphabet': 'GOOGL',
	'Amazon': 'AMZN',
	'Facebook': 'FB',
	'Tesla': 'TSLA',
	'Berkshire Hathaway': 'BRK-A',
	'Taiwan Semiconductor': 'TSM',
	'Alibaba': 'BABA',
	'Visa': 'V',
	'NVIDIA': 'NVDA',
	'JPMorgan Chase': 'JPM',
	'Johnson & Johnson': 'JNJ',
	'Walmart': 'WMT',
	'UnitedHealth': 'UNH',
	'Mastercard': 'MA',
	'Home Depot': 'HD',
	'Bank of America': 'BAC',
	'Procter & Gamble': 'PG',
	'ASML': 'ASML',
	'PayPal': 'PYPL',
	'Disney': 'DIS',
	'Adobe': 'ADBE',
	'Nike': 'NKE',
	'Pfizer': 'PFE',
	'Comcast': 'CMCSA',
	'Eli Lilly': 'LLY',
	'Oracle': 'ORCL',
	'Toyota': 'TM',
	'Exxon Mobil': 'XOM',
	'Coca-Cola': 'KO',
	'Cisco': 'CSCO',
	'Verizon': 'VZ',
	'Netflix': 'NFLX',
	'Salesforce': 'CRM',
	'Danaher': 'DHR',
	'Intel': 'INTC',
	'Abbott Labs': 'ABT',
	'Pepsi': 'PEP',
	'Thermo Fisher Scientific': 'TMO',
	'Novartis': 'NVS',
	'Wells Fargo': 'WFC',
	'Accenture': 'ACN',
	'AbbVie': 'ABBV',
	'AT&T': 'T',
	'Broadcom': 'AVGO',
	'Chevron': 'CVX',
	'Costco': 'COST',
	'Merck': 'MRK',
	'Shopify': 'SHOP',
	'Sea': 'SE',
	'Novo Nordisk':'NVO',
	"AstraZeneca": 'AZN',
	'McDonald': 'MCD',
	'UPS': 'UPS',
	'Qualcomm': 'QCOM',
	'Morgan Stanley': 'MS',
	'Advanced Mirco Devices': 'AMD',
	'Texas Instruments': 'TXN',
	'Linde': 'LIN',
	'Intuit': 'INTU',
	'Blackstone': 'BX',
	'Royal Dutch Shell plc ADR Class B': 'RDS-B',
	'Royal Dutch Shell plc ADR Class A': 'RDS-A',
	'NextEra Energy': 'NEE',
	'SAP': 'SAP',
	"Lowe's": "LOW",
	'Medtronic': 'MDT',
	'Union Pacific': 'UNP',
	'Charles Schwab': 'SCHW',
	'Honeywell': 'HON',
	'Sony': 'SONY',
	'Royal Bank Of Canada': 'RY',
	'T-Mobile': 'TMUS',
	'BlackRock': 'BLK',
	'Philip Morris International': 'PM',
	'Applied Materials': 'AMAT',
	'American Express': 'AXP',
	'Citi': 'C',
	'ServiceNow': 'NOW',
	'BHP Group PlcSponsored': 'BBL',
	'BHP': 'BHP',
	'Goldman Sachs': 'GS',
	'Toronto-Dominion Bank': 'TD',
	'Unilever': 'UL',
	'Raytheon Technologies': 'RTX',
	'Airbnb': 'ABNB',
	'Bristol Myers Squibb': 'BMY',
	'Starbucks': 'SBUX',
	'PetroChina': 'PTR',
	'TotalEnergies': 'TTE',
	'Boeing': 'BA',
	'JD.com': 'JD',
	'Sanofi': 'SNY',
	'Target': 'TGT',
	'Intuitive': 'ISRG',
	'The Estee Lauder Companies': 'EL',
	'CVS': 'CVS',
	'Saudi Aramco': '2222.SR',
	'Tencent': 'TCEHY',
	'Samsung': 'SSNLF',
	'Kweichow Moutai': '600519.SS',
	'Louis Vuitton': 'LVMHF',
	'Nestle': 'NSRGY',
	'Roche': 'RHHBY',
	'ICBC': '1398.HK',
	'LOreal': 'OR.PA',
	'Meituan': 'MPNGF',
	'Ping An Insurance': 'PNGAY',
	'China Construction Bank': '0939.HK',
	'China Merchants Bank': 'CIHKY',
	'Reliance': 'RELIANCE.NS',
	'SoftBank': 'SFTBY',
	'Tata Consultancy Services': 'TCS',
	'Wuliangye Yibin': '000858.SZ',
	'Volkswagen': 'VWAGY',
	'Amgen': 'AMGN',
	'Agricultural Bank of China': 'ACGBY',
	'Siemens': 'SIEGY',
	'Rio Tinto': 'RIO',
	'China Mobile': '0941.HK',
	'Anheuser-Busch': 'BUD',
	'Hermes': 'RMS.PA',
	'Caterpillar': 'CAT',
	'Christian Dior': 'CDI.PA',
	'Keyence': 'KYCCF',
	'Prosus': 'PROSY',
	'CATL': '300750.SZ'

	}

# Declare a dictionary with stock market symbol as key
companies_stock_market = {
	'AAPL': 'Apple',
	'MSFT': 'Microsoft',
	'GOOGL': 'Alphabet',
	'AMZN':  'Amazon',
	'FB': 'Facebook',
	'TSLA': 'Tesla',
	'BRK-A': 'Berkshire Hathaway',
	'TSM': 'Taiwan Semiconductor',
	'BABA': 'Alibaba',
	'V': 'Visa',
	'NVDA': 'NVIDIA',
	'JPM': 'JPMorgan Chase',
	'JNJ': 'Johnson & Johnson',
	'WMT': 'Walmart',
	'UNH': 'UnitedHealth',
	'MA': 'Mastercard',
	'HD': 'Home Depot',
	'BAC': 'Bank of America',
	'PG': 'Procter & Gamble',
	'ASML': 'ASML',
	'PYPL': 'PayPal',
	'DIS': 'Disney',
	'ADBE': 'Adobe',
	'NKE': 'Nike',
	'PFE': 'Pfizer',
	'CMCSA': 'Comcast',
	'LLY': 'Eli Lilly',
	'ORCL': 'Oracle',
	'TM': 'Toyota',
	'XOM': 'Exxon Mobil',
	'KO': 'Coca-Cola',
	'CSCO': 'Cisco',
	'VZ': 'Verizon',
	'NFLX': 'Netflix',
	'CRM': 'Salesforce',
	'DHR': 'Danaher',
	'INTC': 'Intel',
	'ABT': 'Abbott Labs',
	'PEP': 'Pepsi',
	'TMO': 'Thermo Fisher Scientific',
	'NVS': 'Novartis',
	'WFC': 'Wells Fargo',
	'ACN': 'Accenture',
	'ABBV': 'AbbVie',
	'T': 'AT&T',
	'AVGO': 'Broadcom',
	'CVX': 'Chevron',
	'COST': 'Costco',
	'MRK': 'Merck',
	'SHOP': 'Shopify',
	'SE': 'Sea',
	'NVO':'Novo Nordisk',
	'AZN': "AstraZeneca",
	'MCD': 'McDonald',
	'UPS': 'UPS',
	'QCOM': 'Qualcomm',
	'MS': 'Morgan Stanley',
	'AMD': 'Advanced Mirco Devices',
	'TXN': 'Texas Instruments',
	'LIN': 'Linde',
	'INTU': 'Intuit',
	'BX': 'Blackstone',
	'RDS-B': 'Royal Dutch Shell plc ADR Class B',
	'RDS-A': 'Royal Dutch Shell plc ADR Class A',
	'NEE': 'NextEra Energy',
	'SAP': 'SAP',
	"LOW": "Lowe's",
	'MDT': 'Medtronic',
	'UNP': 'Union Pacific',
	'SCHW': 'Charles Schwab',
	'HON': 'Honeywell',
	'SONY': 'Sony',
	'RY': 'Royal Bank Of Canada',
	'TMUS': 'T-Mobile',
	'BLK': 'BlackRock',
	'PM': 'Philip Morris International',
	'AMAT': 'Applied Materials',
	'AXP': 'American Express',
	'C': 'Citi',
	'NOW': 'ServiceNow',
	'BBL': 'BHP Group PlcSponsored',
	'BHP': 'BHP',
	'GS': 'Goldman Sachs',
	'TD': 'Toronto-Dominion Bank',
	'UL': 'Unilever',
	'RTX': 'Raytheon Technologies',
	'ABNB': 'Airbnb',
	'BMY': 'Bristol Myers Squibb',
	'SBUX': 'Starbucks',
	'PTR': 'PetroChina',
	'TTE': 'TotalEnergies',
	'BA': 'Boeing',
	'JD': 'JD.com',
	'SNY': 'Sanofi',
	'TGT': 'Target',
	'ISRG': 'Intuitive',
	'EL': 'The Estee Lauder Companies',
	'CVS': 'CVS',
	'2222.SR': 'Saudi Aramco',
	'TCEHY': 'Tencent',
	'SSNLF': 'Samsung',
	'600519.SS': 'Kweichow Moutai',
	'LVMHF': 'Louis Vuitton',
	'NSRGY':'Nestle',
	'RHHBY':'Roche',
	'1398.HK': 'ICBC',
	'OR.PA':'LOreal',
	'MPNGF':'Meituan',
	'PNGAY': 'Ping An Insurance',
	'0939.HK': 'China Construction Bank',
	'CIHKY': 'China Merchants Bank',
	'RELIANCE.NS': 'Reliance',
	'SFTBY':'SoftBank ',
	'TCS':'Tata Consultancy Services',
	'000858.SZ': 'Wuliangye Yibin',
	'VWAGY':'Volkswagen',
	'AMGN': 'Amgen',
	'ACGBY':'Agricultural Bank of China',
	'SIEGY': 'Siemens',
	'RIO':'Rio Tinto',
	'0941.HK':'China Mobile',
	'BUD':'Anheuser-Busch',
	'RMS.PA': 'Hermes',
	'CAT': 'Caterpillar',
	'CDI.PA':'Christian Dior',
	'KYCCF':'Keyence',
	'PROSY':'Prosus',
	'300750.SZ': 'CATL'
	}